const indianStatesObjects = [
    { title: "Andaman and Nicobar Islands" },
    { title: "Andhra Pradesh" },
    { title: "Arunachal Pradesh" },
    { title: "Assam" },
    { title: "Bihar" },
    { title: "Chandigarh" },
    { title: "Chhattisgarh" },
    { title: "Dadra and Nagar Haveli" },
    { title: "Daman and Diu" },
    { title: "Delhi" },
    { title: "Goa" },
    { title: "Gujarat" },
    { title: "Haryana" },
    { title: "Himachal Pradesh" },
    { title: "Jammu and Kashmir" },
    { title: "Jharkhand" },
    { title: "Karnataka" },
    { title: "Kerala" },
    { title: "Ladakh" },
    { title: "Lakshadweep" },
    { title: "Madhya Pradesh" },
    { title: "Maharashtra" },
    { title: "Manipur" },
    { title: "Meghalaya" },
    { title: "Mizoram" },
    { title: "Nagaland" },
    { title: "Odisha" },
    { title: "Puducherry" },
    { title: "Punjab" },
    { title: "Rajasthan" },
    { title: "Sikkim" },
    { title: "Tamil Nadu" },
    { title: "Telangana" },
    { title: "Tripura" },
    { title: "Uttar Pradesh" },
    { title: "Uttarakhand" },
    { title: "West Bengal" }
  ];

  export default indianStatesObjects